on:
  push:
    branches: main
  pull_request:
    branches: main

name: python-install-run

jobs: python-install-run:
    name: Install and run a simple test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.9
      
      - uses: actions/setup-python@v2
          with: 
            python-version: 3.9

      - name: install dependencies
        if: always()
        run: |
          python3 -m pip install --upgrade pip
          pip3 install numpy

